# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

aliases:
  - &current_workspace
    attach_workspace: { at: "~/repo" }

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:12

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install monorepo ROOT dependencies
          command: yarn install
      - run:
          name: Install monorepo PACKAGES dependencies
          command: npx lerna bootstrap -- --non-interactive --cache-folder ~/.cache/yarn
      - persist_to_workspace:
          root: "~/repo"
          paths:
            - "change/*"
            - "packages/*"
            - "node_modules/*"
            - ".eslintignore"
            - ".eslintrc.js"
            - ".prettierrc.js"
            - "package.json"
            - "lerna.json"

  release:
    <<: *defaults
    steps:
      - checkout
      - *current_workspace
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
      - run:
          name: Release
          command: yarn release

workflows:
  version: 2
  build_and_release:
    jobs:
      - install

      - release:
          requires:
            - install
